name: Deploy Static Application to Ubuntu Apache2 Server

on:
  
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  
  workflow_dispatch:


jobs:
  
  deployment:
    
    runs-on: ubuntu-latest

    steps:
      
      - name: Clone the Code
        uses: actions/checkout@v3

      - name: Verify the Code is Cloned
        run: ls -la

      - name: Copy the Code to the Server
        uses: easingthemes/ssh-deploy@main
        env: 
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          ARGS: "-rltgoDzv0"
          SOURCE: "mysite.html"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
